---

- name: checksum
  become: false
  delegate_to: localhost
  run_once: true
  block:
    - name: get checksum list
      bodsch.scm.github_checksum:
        project: grafana
        repository: loki
        checksum_file: SHA256SUMS
        user: "{{ lookup('env', 'GH_USER') | default(omit) }}"
        password: "{{ lookup('env', 'GH_TOKEN') | default(omit) }}"
        architecture: "{{ ansible_architecture }}"
        system: "{{ ansible_facts.system }}"
        version: "v{{ promtail_version }}"
      register: _latest_checksum

    - name: define checksum for {{ go_arch }} architecture
      ansible.builtin.set_fact:
        __promtail_checksum: "{{ _latest_checksum.checksums | promtail_checksum('promtail', 'linux', go_arch) }}"
      when:
        - _latest_checksum.rc == 0
        - _latest_checksum.checksum is defined
        - _latest_checksum.checksum | string | length > 0

- name: download promtail binary archive
  become: false
  delegate_to: "{{ promtail_delegate_to }}"
  run_once: "{{ 'false' if promtail_direct_download else 'true' }}"
  ansible.builtin.get_url:
    url: "{{ promtail_release_download_url }}/download/v{{ promtail_version }}/promtail-linux-amd64.zip"
    dest: "{{ promtail_local_tmp_directory }}/promtail-linux-amd64.zip"
    checksum: "sha256:{{ __promtail_checksum }}"
    mode: 0660
  register: _download_archive
  until: _download_archive is succeeded
  retries: 5
  delay: 2
  check_mode: false

- name: extract promtail archive
  become: false
  delegate_to: "{{ promtail_delegate_to }}"
  run_once: "{{ 'false' if promtail_direct_download else 'true' }}"
  ansible.builtin.unarchive:
    src: "{{ promtail_local_tmp_directory }}/promtail-linux-amd64.zip"
    dest: "{{ promtail_local_tmp_directory }}/"
    copy: false

...
