---

- name: define checksum
  become: false
  delegate_to: localhost
  run_once: true
  block:
    - name: get checksum list
      ansible.builtin.set_fact:
        __promtail_checksums: "{{ lookup('url', 'https://github.com/grafana/loki/releases/download/v' + promtail_version + '/SHA256SUMS', wantlist=True) | list }}"
      run_once: true

    - name: get checksum for {{ go_arch }} architecture
      ansible.builtin.set_fact:
        __promtail_checksum: "{{ __promtail_checksums | promtail_checksum('promtail', 'linux', go_arch) }}"

- name: download promtail binary archive
  become: false
  delegate_to: "{{ promtail_delegate_to }}"
  run_once: "{{ 'false' if promtail_direct_download else 'true' }}"
  ansible.builtin.get_url:
    url: "{{ promtail_release_download_url }}/download/v{{ promtail_version }}/promtail-linux-amd64.zip"
    dest: "{{ promtail_local_tmp_directory }}/promtail-linux-amd64.zip"
    checksum: "sha256:{{ __promtail_checksum }}"
    mode: 0660
  register: _download_archive
  until: _download_archive is succeeded
  retries: 5
  delay: 2
  check_mode: false

- name: extract promtail archive
  become: false
  delegate_to: "{{ promtail_delegate_to }}"
  run_once: "{{ 'false' if promtail_direct_download else 'true' }}"
  ansible.builtin.unarchive:
    src: "{{ promtail_local_tmp_directory }}/promtail-linux-amd64.zip"
    dest: "{{ promtail_local_tmp_directory }}/"
    copy: false

...
