---

- block:
    - name: get checksum list
      set_fact:
        __promtail_checksums: "{{ lookup('url', 'https://github.com/grafana/loki/releases/download/v' + promtail_version + '/SHA256SUMS', wantlist=True) | list }}"
      run_once: true

    - name: get checksum for {{ go_arch }} architecture
      set_fact:
        __promtail_checksum: "{{ __promtail_checksums | promtail_checksum('promtail', 'linux', go_arch) }}"
  delegate_to: localhost

- name: download promtail binary archive
  become: false
  delegate_to: "{{ promtail_delegate_to }}"
  get_url:
    url: "{{ promtail_release_download_url }}/download/v{{ promtail_version }}/promtail-linux-amd64.zip"
    dest: "{{ promtail_local_tmp_directory }}/promtail-linux-amd64.zip"
    checksum: "sha256:{{ __promtail_checksum }}"
  register: _download_archive
  until: _download_archive is succeeded
  retries: 5
  delay: 2
  check_mode: false

- name: extract promtail archive
  become: false
  delegate_to: "{{ promtail_delegate_to }}"
  unarchive:
    src: "{{ promtail_local_tmp_directory }}/promtail-linux-amd64.zip"
    dest: "{{ promtail_local_tmp_directory }}/"
    copy: false

- name: detect binary file for promtail
  become: false
  delegate_to: "{{ promtail_delegate_to }}"
  stat:
    path: "{{ promtail_local_tmp_directory }}/promtail-linux-amd64"
  register: stat_file_binary

- name: fail when extracted binary are missing
  fail:
    msg: "missing extracted binary on ansible controller"
  when:
    - not stat_file_binary.stat.exists

- block:
    - name: propagate promtail binaries
      copy:
        src: "{{ promtail_local_tmp_directory }}/promtail-linux-amd64"
        dest: "{{ promtail_install_path }}/promtail"
        mode: 0755
        owner: "{{ promtail_system_user }}"
        group: "{{ promtail_system_group }}"
        remote_src: "{{ 'true' if promtail_direct_download else 'false' }}"

    - name: make files executable
      file:
        path: "{{ promtail_install_path }}/promtail"
        mode: 0755
        owner: "{{ promtail_system_user }}"
        group: "{{ promtail_system_group }}"
  when:
    - stat_file_binary.stat.exists

...
