---

- name: create promtail data directory
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ promtail_system_user }}"
    group: "{{ promtail_system_group }}"
    mode: 0755
  loop:
    - "{{ promtail_storage_dir }}"

- name: create systemd service unit
  template:
    src: "init/systemd/promtail.service.j2"
    dest: "{{ systemd_lib_directory }}/promtail.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - daemon-reload
    - restart promtail

...
