---

- name: detect extracted binary file for promtail on {{ promtail_delegate_to }}
  become: false
  delegate_to: "{{ promtail_delegate_to }}"
  run_once: "{{ 'false' if promtail_direct_download else 'true' }}"
  ansible.builtin.stat:
    path: "{{ promtail_local_tmp_directory }}/promtail-linux-amd64"
  register: stat_file_binary

- name: fail when extracted binary are missing
  ansible.builtin.fail:
    msg: "missing extracted binary on ansible controller"
  when:
    - not stat_file_binary.stat.exists

- name: propagate promtail binaries
  ansible.builtin.copy:
    src: "{{ promtail_local_tmp_directory }}/promtail-linux-amd64"
    dest: "{{ promtail_install_path }}/promtail"
    mode: 0755
    owner: "{{ promtail_system_user }}"
    group: "{{ promtail_system_group }}"
    remote_src: "{{ 'true' if promtail_direct_download else 'false' }}"
  when:
    - stat_file_binary.stat.exists

- name: make files executable
  ansible.builtin.file:
    path: "{{ promtail_install_path }}/promtail"
    mode: 0755
    owner: "{{ promtail_system_user }}"
    group: "{{ promtail_system_group }}"

- name: create link to binary
  ansible.builtin.file:
    src: "{{ promtail_install_path }}/promtail"
    dest: /usr/bin/promtail
    state: link
    force: true
  notify:
    - restart promtail

- name: create promtail data directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ promtail_system_user }}"
    group: "{{ promtail_system_group }}"
    mode: 0755
  loop:
    - "{{ promtail_storage_dir }}"

- name: create systemd service unit
  ansible.builtin.template:
    src: "init/systemd/promtail.service.j2"
    dest: "{{ systemd_lib_directory }}/promtail.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - daemon-reload
  when:
    - ansible_service_mgr | lower == "systemd"

- name: create service configuration
  ansible.builtin.template:
    src: "promtail.j2"
    dest: "{{ promtail_defaults_directory }}/promtail"
    force: true
    owner: root
    group: "{{ promtail_system_group }}"
    mode: 0640
  notify:
    - restart promtail

- name: create local facts
  ansible.builtin.template:
    src: ansible_facts.j2
    dest: /etc/ansible/facts.d/promtail.fact
    mode: 0755

...
