---

- name: create link to binary
  file:
    src: "{{ promtail_install_path }}/promtail"
    dest: /usr/bin/promtail
    state: link
    force: true
  notify:
    - restart promtail

- name: create promtail data directory
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ promtail_system_user }}"
    group: "{{ promtail_system_group }}"
    mode: 0755
  loop:
    - "{{ promtail_storage_dir }}"

- name: create systemd service unit
  template:
    src: "init/systemd/promtail.service.j2"
    dest: "{{ systemd_lib_directory }}/promtail.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - daemon-reload
    - restart promtail

- name: create local facts
  template:
    src: ansible_facts.j2
    dest: /etc/ansible/facts.d/promtail.fact
    mode: 0755
...
