---

- name: restart promtail if needed
  ansible.builtin.meta: flush_handlers

- name: ensure promtail is enabled on boot
  become: true
  ansible.builtin.service:
    name: promtail
    enabled: true
    state: started

...
