---

- name: loki
  src: https://github.com/bodsch/ansible-loki.git
  scm: git
  # version: 1.0.0

- name: nginx
  # src: https://github.com/geerlingguy/ansible-role-nginx.git
  # version: 3.1.0
  src: https://github.com/bodsch/ansible-role-nginx.git
  scm: git
  version: fix/archlinux-dont-need-pidfile

...
