---

promtail_version: "2.6.1"

promtail_server:
  http_listen_address: "127.0.0.1"
  http_listen_port: 9080
  log_level: debug

promtail_scrape_configs:
  # file_sd
  - job_name: file_sd
    file_sd_configs:
      - files:
          - "{{ promtail_config_dir }}//file_sd/*.yml"
          - "{{ promtail_config_dir }}//file_sd/*.yaml"
          - "{{ promtail_config_dir }}//file_sd/*.json"
  # example static config
  # - job_name: system
  #   static_configs:
  #     - targets:
  #         - localhost
  #       labels:
  #         job: varlogs
  #         host: "{{ ansible_fqdn }}"
  #         agent: promtail
  #         __path__: /var/log/*.log
  #
  # # example journald config
  # - job_name: journal
  #   journal:
  #     max_age: 12h
  #     labels:
  #       job: systemd-journal
  #   relabel_configs:
  #     - source_labels:
  #         - __journal__systemd_unit
  #       target_label: 'unit'

  # example syslog config
  - job_name: syslog
    syslog:
      listen_address: 0.0.0.0:1514
      labels:
        job: "syslog"
    relabel_configs:
      - source_labels:
          - __syslog_message_hostname
        target_label: 'host'

  - job_name: nginx_access
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          host: "{{ ansible_fqdn }}"
          log_level: access
          agent: promtail
          __path__: /var/log/nginx/**access.log

    pipeline_stages:
      # anonymisier latest octet
      - replace:
          expression: '(?:[0-9]{1,3}\.){3}([0-9]{1,3})'
          replace: '***'

  # - job_name: nginx_error
  #   static_configs:
  #     - targets:
  #         - localhost
  #       labels:
  #         job: nginx
  #         host: "{{ ansible_fqdn }}"
  #         log_level: error
  #         agent: promtail
  #         env: development
  #         __path__: /var/log/nginx/*/*error.log
  #
  #   pipeline_stages:
  #     - match:
  #         selector: '{log_level="error"}'
  #         stages:
  #         # parse error.log
  #         - regex:
  #             expression: '^(?P<timestamp>\d{4}/\d{2}/\d{2}\ \d{2}:\d{2}:\d{2})\ \[(?P<severity>emerg|alert|crit|error|warn|notice|info)\]\ (?P<process_id>\d+)\#(?P<thread_id>\d+):\ \*(?P<connection_id>\d+)\ (?P<error>.+?)(?:\ while\ (?P<context>.+?))?,\ client:\ (?P<client_ip>\d+\.\d+\.\d+\.\d+),\ server:\ (?P<server>.+?)(?:,\ request:\ \"(?P<request_method>[A-Z]+?)\ (?P<request_path>\/.+?)\ (?P<request_protocol>.+?)\")?(?:,\ upstream:\ \"(?P<upstream>.+?)\")?(?:,\ host:\ \"(?P<host>.+?)\")?(?:,\ referrer:\ \"(?P<referrer>.+?)\")?$'
  #         - labels:
  #             timestamp:
  #             severity:
  #             process_id:
  #             thread_id:
  #             connection_id:
  #             error:
  #             context:
  #             client_ip:
  #             server:
  #             request_method:
  #             request_path:
  #             request_protocol:
  #             upstream:
  #             host:
  #             referrer:

...

# https://regex101.com/r/oPEqMk/1
#     ^(?P<timestamp>\d{4}/\d{2}/\d{2}\ \d{2}:\d{2}:\d{2})
#     \ \[(?P<severity>emerg|alert|crit|error|warn|notice|info)\]
#     \ (?P<process_id>\d+)
#     \#(?P<thread_id>\d+):
#     \ \*(?P<connection_id>\d+)
#     \ (?P<error>.+?)
#     (?:\ while\ (?P<context>.+?))?
#     ,\ client:\ (?P<client_ip>\d+\.\d+\.\d+\.\d+)
#     ,\ server:\ (?P<server>.+?)
#     (?:,\ request:\ \"(?P<request_method>[A-Z]+?)
#         \ (?P<request_path>\/.+?)
#         \ (?P<request_protocol>.+?)\")?
#     (?:,\ upstream:\ \"(?P<upstream>.+?)\")?
#     (?:,\ host:\ \"(?P<host>.+?)\")?
#     (?:,\ referrer:\ \"(?P<referrer>.+?)\")?
#     $
