---

name: promtail with custom scrape configs

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - "CI"
    branches:
      - main
    types:
      - completed

defaults:
  run:
    working-directory: 'ansible-promtail'

jobs:
  deb:
    name: "${{ matrix.image }} / ansible: ${{ matrix.ansible-version }}"
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'schedule' || github.event.workflow_run.conclusion == 'success' }}
    strategy:
      fail-fast: false
      matrix:
        image:
          - debian:11
        ansible-version:
          - '6.1'
        scenario:
          - custom-scrape-configs
    steps:
      - name: check out the codebase.
        uses: actions/checkout@v3
        with:
          path: 'ansible-promtail'

      - name: 🐍 set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test-requirements.txt

      - name: test with tox
        run: |
          tox -e ansible_$(printf "${{ matrix.ansible-version }}") \
            -- molecule test --scenario-name "${{ matrix.scenario }}"
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          DISTRIBUTION: ${{ matrix.image }}
